### ISSUE TITLE
Issue with infinite authorization still exists?

### ISSUE THREAD

**Issue by thelelanator** [Vap0r1ze/inscrybe-with-friends#5]
I heard you were working on an update to fix the game not working if no one plays it for a week, how's that coming along?

**Comment by Vap0r1ze** [comment]
Hi I'm gonna close this since this is the result of #4, but thank you for reminding me I had totally forgotten. I'll see if I can get this done today! Feel free to bump the #4 if I'm not able to do it today and forget again >.>
